name: 'Publish GitHub pages'
description: 'Publish static files to branch with GitHub pages'
inputs:
  branch:
    description: 'This is the branch you wish to deploy to, for example gh-pages or docs.'
    required: false
    default: gh-pages
  folder:
    description: >
      The folder in your repository that you want to deploy. 
      If you wish to deploy the root directory you can place a . here.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Copy files to another directory
      shell: bash
      run: >
        mkdir /tmp/pages && 
        cp -r ${{ inputs.folder }}/** /tmp/pages &&
        ls -la /tmp/pages

    - name: Checkout target branch
      shell: bash
      run: >
        git config user.name "GitHub Pages Action" &&
        git config user.email "github-pages-action@github.com"  

    - name: Checkout target branch
      shell: bash
      run: >
        git switch ${{ inputs.branch }} || 
        git checkout --orphan ${{ inputs.branch }}
    - name: Commit pages static files
      shell: bash
      run: >
        set +euo pipefail;
        git rm -rf . &&
        git restore .git .github .ssh .nojekyll CNAME &&
        ls -la /tmp/pages &&
        cp -r /tmp/pages/** ./ &&
        git add -A &&
        git commit -m 'Update GitHub pages' &&
        git push --set-upstream origin ${{ inputs.branch }}
